<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <!-- 1. DICHIARA IL PARENT (Fondamentale!) -->
  <parent>
    <groupId>it.uninsubria.cinemax</groupId>
    <artifactId>Lab-B-Cinemax</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <!-- groupId e version vengono ereditati dal parent, basta l'artifactId -->
  <artifactId>server-cm</artifactId>
  <packaging>jar</packaging>
  <name>server-cm</name>
  <description>Modulo server Cinemax con DAO e logica di connessione</description>
  
  <dependencies>
    <!-- Dipendenza ai contratti -->
    <dependency>
      <groupId>it.uninsubria.cinemax</groupId>
      <artifactId>cinemax-contracts</artifactId>
      <version>0.0.1-SNAPSHOT</version>
    </dependency>
    
    <!-- PostgreSQL: rimuovi la versione qui! La prende in automatico dal dependencyManagement del Parent -->
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>