--
-- PostgreSQL database dump
--

\restrict Ppnxs98j1ozcULbEJeoEHNJzxgjRhd2AfwmhsJ8zLmxuI9V5jn6B7GB8CgnlHsu

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.0

-- Started on 2026-08-26 18:38:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5059 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16385)
-- Name: Films; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Films" (
    titolo_film character varying(255) CONSTRAINT "Films_titoloFilm_not_null" NOT NULL,
    genere character varying(255),
    regista character varying(255),
    anno smallint NOT NULL,
    durata_minuti smallint,
    eta_minima smallint,
    id integer NOT NULL
);


ALTER TABLE public."Films" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16393)
-- Name: Films_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Films" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Films_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16394)
-- Name: Prenotazioni; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Prenotazioni" (
    id integer CONSTRAINT prenotazioni_id_not_null NOT NULL,
    id_utente integer CONSTRAINT prenotazioni_id_utente_not_null NOT NULL,
    id_proiezione integer CONSTRAINT prenotazioni_id_proiezione_not_null NOT NULL,
    numero_posti integer
);


ALTER TABLE public."Prenotazioni" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16400)
-- Name: Prenotazioni_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Prenotazioni" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Prenotazioni_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16401)
-- Name: Proiezioni; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Proiezioni" (
    data_ora_proiezione timestamp without time zone,
    id_film integer,
    id integer NOT NULL,
    prezzo_biglietto numeric(4,2)
);


ALTER TABLE public."Proiezioni" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16405)
-- Name: Proiezioni_pianificate; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."Proiezioni_pianificate" AS
 SELECT proiezioni.id AS id_proiezione,
    films.id AS id_film,
    proiezioni.data_ora_proiezione,
    films.titolo_film AS titolofilm,
    films.genere,
    films.regista,
    films.anno,
    films.durata_minuti AS durataminuti,
    films.eta_minima AS etaminima,
    proiezioni.prezzo_biglietto,
    COALESCE(p.totale_posti, (0)::bigint) AS totale_posti_prenotati
   FROM ((public."Proiezioni" proiezioni
     JOIN public."Films" films ON ((proiezioni.id_film = films.id)))
     LEFT JOIN ( SELECT "Prenotazioni".id_proiezione,
            sum("Prenotazioni".numero_posti) AS totale_posti
           FROM public."Prenotazioni"
          GROUP BY "Prenotazioni".id_proiezione) p ON ((proiezioni.id = p.id_proiezione)))
  WHERE (proiezioni.data_ora_proiezione >= CURRENT_DATE);


ALTER VIEW public."Proiezioni_pianificate" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16410)
-- Name: Utenti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Utenti" (
    nome character varying(255) CONSTRAINT "Utente_nome_not_null" NOT NULL,
    cognome character varying(255) CONSTRAINT "Utente_cognome_not_null" NOT NULL,
    username character varying(255) CONSTRAINT "Utente_username_not_null" NOT NULL,
    password character varying(32) CONSTRAINT "Utente_password_not_null" NOT NULL,
    data_nascita date,
    domicilio character varying(255) CONSTRAINT "Utente_domicilio_not_null" NOT NULL,
    ruolo character varying DEFAULT 'cliente'::character varying CONSTRAINT "Utente_ruolo_not_null" NOT NULL,
    id integer CONSTRAINT "Utente_id_not_null" NOT NULL
);


ALTER TABLE public."Utenti" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16423)
-- Name: Prenotazioni_pianificate; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."Prenotazioni_pianificate" AS
 SELECT proiezioni.data_ora_proiezione,
    prenotazioni.id AS id_prenotazione,
    proiezioni.id_proiezione,
    utente.id AS id_utente,
    utente.nome,
    utente.cognome,
    prenotazioni.numero_posti AS num_posti,
    proiezioni.prezzo_biglietto,
    ((prenotazioni.numero_posti)::numeric * proiezioni.prezzo_biglietto) AS totale,
    proiezioni.titolofilm
   FROM ((public."Prenotazioni" prenotazioni
     JOIN public."Utenti" utente ON ((prenotazioni.id_utente = utente.id)))
     JOIN public."Proiezioni_pianificate" proiezioni ON ((prenotazioni.id_proiezione = proiezioni.id_proiezione)))
  WHERE (proiezioni.data_ora_proiezione >= CURRENT_DATE)
  ORDER BY proiezioni.data_ora_proiezione;


ALTER VIEW public."Prenotazioni_pianificate" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16428)
-- Name: Proiezioni_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Proiezioni" ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Proiezioni_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16429)
-- Name: Proiezioni_storiche; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public."Proiezioni_storiche" AS
 SELECT proiezioni.id AS id_proiezione,
    films.id AS id_film,
    proiezioni.data_ora_proiezione,
    films.titolo_film AS titolofilm,
    films.genere,
    films.regista,
    films.anno,
    films.durata_minuti AS durataminuti,
    films.eta_minima AS etaminima,
    proiezioni.prezzo_biglietto
   FROM (public."Proiezioni" proiezioni
     JOIN public."Films" films ON ((proiezioni.id_film = films.id)))
  ORDER BY proiezioni.data_ora_proiezione, films.titolo_film;


ALTER VIEW public."Proiezioni_storiche" OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16433)
-- Name: Utente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Utenti" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Utente_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 4890 (class 2606 OID 16440)
-- Name: Films Films_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Films"
    ADD CONSTRAINT "Films_pkey" PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 16442)
-- Name: Prenotazioni Prenotazioni_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prenotazioni"
    ADD CONSTRAINT "Prenotazioni_pkey" PRIMARY KEY (id);


--
-- TOC entry 4894 (class 2606 OID 16444)
-- Name: Proiezioni Proiezioni_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Proiezioni"
    ADD CONSTRAINT "Proiezioni_pkey" PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 16446)
-- Name: Utenti Utente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Utenti"
    ADD CONSTRAINT "Utente_pkey" PRIMARY KEY (id);


--
-- TOC entry 4900 (class 2606 OID 16448)
-- Name: Utenti Utente_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Utenti"
    ADD CONSTRAINT "Utente_username_key" UNIQUE (username);


--
-- TOC entry 4888 (class 2606 OID 16449)
-- Name: Utenti chk_tipo; Type: CHECK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE public."Utenti"
    ADD CONSTRAINT chk_tipo CHECK (((ruolo)::text = ANY (ARRAY[('cliente'::character varying)::text, ('proiezionista'::character varying)::text, ('bigliettaio'::character varying)::text]))) NOT VALID;


--
-- TOC entry 4896 (class 2606 OID 16451)
-- Name: Proiezioni data proiezione unica; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Proiezioni"
    ADD CONSTRAINT "data proiezione unica" UNIQUE (data_ora_proiezione);


--
-- TOC entry 4903 (class 2606 OID 16452)
-- Name: Proiezioni Proiezioni_id_film_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Proiezioni"
    ADD CONSTRAINT "Proiezioni_id_film_fkey" FOREIGN KEY (id_film) REFERENCES public."Films"(id) NOT VALID;


--
-- TOC entry 4901 (class 2606 OID 16457)
-- Name: Prenotazioni ref_proiezioni; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prenotazioni"
    ADD CONSTRAINT ref_proiezioni FOREIGN KEY (id_proiezione) REFERENCES public."Proiezioni"(id);


--
-- TOC entry 4902 (class 2606 OID 16462)
-- Name: Prenotazioni ref_utente; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Prenotazioni"
    ADD CONSTRAINT ref_utente FOREIGN KEY (id_utente) REFERENCES public."Utenti"(id);


-- Completed on 2026-08-26 18:38:39

--
-- PostgreSQL database dump complete
--

\unrestrict Ppnxs98j1ozcULbEJeoEHNJzxgjRhd2AfwmhsJ8zLmxuI9V5jn6B7GB8CgnlHsu

